spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vuelos_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      data-locations: classpath:data-postgres.sql
